# Generated by Django 3.0.5 on 2020-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
