# Generated by Django 3.0.5 on 2020-04-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='web_templates/static/Images')),
                ('product_price', models.IntegerField()),
                ('product_discount', models.IntegerField()),
                ('product_stock', models.IntegerField(default=1)),
                ('product_rating', models.IntegerField(default=1)),
                ('product_description', models.TextField(default="It's a good product to buy :)")),
                ('slug', models.SlugField(default='default_slug_name')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.ProductBrand')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.ProductType')),
            ],
        ),
    ]
