# Generated by Django 3.0.5 on 2020-04-23 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_wallet', models.IntegerField(default=5000)),
                ('user_profile_pic', models.ImageField(upload_to='web_templates/static/Images/User_Profile_Pics')),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(default='Prefer not to say', max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('billing_address', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
