# Generated by Django 3.0.5 on 2020-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200423_1831'),
        ('home_page', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_addresses',
            field=models.ManyToManyField(to='billing.BillingAddress'),
        ),
    ]
