# Generated by Django 3.0.5 on 2020-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20200423_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(default='default_Brand_slug_name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(default='default_Type_slug_name'),
        ),
    ]
